require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'lib/**/*'
    - 'node_modules/**/*'
    - 'script/**/*'
    - 'tmp/**/*'
    - 'spec/**/*'
    - 'vendor/**/*'
    - 'Gemfile'
    - 'Rakefile'
    - 'config.ru'

Style/Documentation:
  Description: 'Checks for missing top-level class and module documentation.'
  Enabled: false
Style/InlineComment:
  Description: 'Avoid inline comments.'
  Enabled: false
Style/FrozenStringLiteralComment:
  Description: 'Add the frozen string literal comment to the top of files.'
  Enabled: false
Style/ClassAndModuleChildren:
  Description: 'Checks style of children classes and modules.'
  Enabled: false
Style/EmptyMethod:
  Description: 'Avoid empty methods.'
  Enabled: false
Style/StringLiterals:
  Description: 'Checks if uses of quotes match the configured preference.'
  Enabled: false
Style/MissingRespondToMissing:
  Description: 'Checks for missing respond_to_missing? when using method_missing.'
  Enabled: false
Metrics/MethodLength:
  Description: 'Avoid methods longer than 15 lines of code.'
  Max: 15
Metrics/AbcSize:
  Description: 'A calculated magnitude based on number of assignments, branches, and
    conditions.'
  Enabled: false
RSpec/MultipleExpectations:
  Description: 'Checks for multiple expectations in one example.'
  Max: 3
RSpec/ExampleLength:
  Description: 'Checks for long example groups.'
  Max: 10
